services:
  postgres:
    image: postgres:15
    container_name: mottu_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mottu
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mottu"]
      interval: 5s
      timeout: 3s
      retries: 10

  api:
    container_name: rental_api
    build:
      context: ..
      dockerfile: src/Rental.Api/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__Default: Host=postgres;Port=5432;Database=mottu;Username=postgres;Password=postgres
    ports:
      - "5000:8080"
    restart: unless-stopped
    volumes:
      - ../src/Rental.Api/storage:/app/storage  # se estiver salvando arquivos locais

volumes:
  postgres_data:
